name: EBAC CI Mobile

on:
  push:
    branches: [ ci ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Puxar o código
      - uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      # 3️⃣ Instalar dependências
      - name: Install Dependencies
        run: npm install

      # 4️⃣ Rodar os testes
      - name: Run Tests
        run: npm t

      # 5️⃣ Gerar relatório Allure
      - name: Generate Allure Report
        run: |
          npx allure generate ./allure-results --clean -o ./allure-report

      # 6️⃣ Publicar relatório no branch gh-pages usando PAT
      - name: Publish Allure Report
        if: always()
        run: |
          git config user.name "JoaoLopes5"
          git config user.email "sm.fisher18@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN1 }}@github.com/JoaoLopes5/Teste-iOS.git
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          git rm -rf . || echo "No files to remove"
          cp -r ./allure-report/* .
          git add .
          git commit -m "Update Allure Report [ci skip]" || echo "No changes to commit"
          git push origin gh-pages --force
