name: EBAC CI Mobile

on:
  push:
    branches: [ ci ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      # 3. Instalar dependências
      - name: Install Dependencies
        run: npm ci

      # 4. Rodar testes
      - name: Run Tests
        run: npm t

      # 5. Gerar relatório Allure
      - name: Generate Allure Report
        run: npx allure generate ./allure-results --clean -o ./allure-report

      # 6. Publicar relatório no GitHub Pages
      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
