name: EBAC CI Mobile

on:
  push:
    branches: [ ci ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Puxar o código
      - uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      # 3️⃣ Instalar dependências
      - name: Install Dependencies
        run: npm install

      # 4️⃣ Rodar os testes
      - name: Run Tests
        run: npm t

      # 5️⃣ Gerar relatório Allure (ajuste se necessário)
      - name: Generate Allure Report
        run: |
          npx allure generate ./allure-results --clean -o ./allure-report

      # 6️⃣ Publicar relatório no branch gh-pages usando PAT
      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./allure-report
          # Mantém histórico de commits (opcional)
          keep_files: true
